FROM ultralytics/ultralytics:latest

WORKDIR /app

COPY apps/inference/requirements-gpu.txt /app/requirements-gpu.txt
RUN pip install --no-cache-dir -r requirements-gpu.txt

COPY . /app

EXPOSE 5001

CMD ["gunicorn", "--workers", "1", "--threads", "1", "--timeout", "120", "--bind", "0.0.0.0:5001", "apps.inference.app:app"]
